name: Generate Radar Image

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour, adjust as needed
  workflow_dispatch:  # allows manual trigger

jobs:
  plot-radar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # safe because Py-ART is removed

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install --upgrade --force-reinstall -r requirements.txt

      - name: Verify Python & packages
        run: |
          python --version
          python -m pip list

      - name: Run radar plotting script
        run: python scripts/plotnexrad.py  # update path if needed

      - name: Upload generated image
        uses: actions/upload-artifact@v4
        with:
          name: nexrad-image
          path: nexrad_base_reflectivity_map_*.png
  
