name: Update weather data

on:
  schedule:
    # every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: {}

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run fetch script
        env:
          AMBIENT_APP_KEY: ${{ secrets.AMBIENT_APP_KEY }}
          AMBIENT_API_KEY: ${{ secrets.AMBIENT_API_KEY }}
        run: |
          python scripts/fetch_data.py

      - name: Commit and push data files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/stations.yml docs/data/stations.json || true
          git commit -m "Update weather data" || echo "No changes to commit"
          git push
